[workspace]
resolver = "2"
members = [
  "examples/custom-binary",
  "trailbase-cli",
  "trailbase-core",
  "trailbase-extension",
  "trailbase-sqlite",
  "vendor/sqlean",
]
default-members = [
  "trailbase-cli",
  "trailbase-core",
  "trailbase-extension",
  "trailbase-sqlite",
]
exclude = [
  "vendor/refinery",
]

# https://doc.rust-lang.org/cargo/reference/profiles.html
[profile.release]
panic = "unwind"
opt-level = 3
# PGO doesn't work with LTO: https://github.com/llvm/llvm-project/issues/57501
# lto = "off"
lto = true
codegen-units = 1

# Workaround for https://github.com/gwenn/lemon-rs/issues/78. sqlite3-parser
# requires 1+MB stack frames to parse trivial SQL statements, which is larger
# than Window's default stack size of 1MB. This is due to the rust compiler not
# overlapping stack variables of disjoint branches in dev mode and instead
# allocating them all.
[profile.dev.package.sqlite3-parser]
opt-level = 1

[workspace.dependencies]
trailbase-refinery-core = { path = "vendor/refinery/refinery_core", version = "0.8.15", default-features = false, features = ["rusqlite-bundled"] }
trailbase-refinery-macros = { path = "vendor/refinery/refinery_macros", version = "0.8.15" }
libsqlite3-sys = { version = "0.30.1", features = ["bundled"] }
rusqlite = { version = "^0.32.1", default-features = false, features = [
    "bundled",
    "column_decltype",
    "load_extension",
    "modern_sqlite",
    "functions",
    "limits",
    "backup",
    "hooks",
    "preupdate_hook",
] }
trailbase-sqlean = { path = "vendor/sqlean", version = "^0.0.1" }
trailbase-extension = { path = "trailbase-extension", version = "^0.1.0" }
trailbase-sqlite = { path = "trailbase-sqlite", version = "^0.1.0" }
trailbase = { path = "trailbase-core", version = "^0.0.2" }
